### ISSUE TITLE
Publishing to a repo

### ISSUE THREAD

**Issue by dpassen** [WJCFerguson/textsize#1]
Do you have any intentions of publishing this to MELPA or somewhere similar?

**Comment by WJCFerguson** [comment]
Good point - I'd forgotten about that.  I will look into it.  LMK if you're using it and see bugs etc.

**Comment by WJCFerguson** [comment]
PR in, hopefully it'll get accepted soon.

**Comment by dpassen** [comment]
Thanks so much

**Comment by WJCFerguson** [comment]
It is done, finally.  Sorry progress on this was slow.

Please note that `textsize-setup` defun is now gone and instead it is a minor mode.  Now it's in Melpa I'll take more care to maintain compatibility, but I've been brutal and just switched it.

**Comment by dpassen** [comment]
Thanks so much!
